# Development Environment Configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/apontaja_dev
    username: ${DB_USERNAME:apontaja}
    password: ${DB_PASSWORD:apontaja}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: false

# Development logging
logging:
  level:
    com.apontaja.backend: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
